name: Serenity BDD Tests
# IMPORTANTE: Éste pipeline se ejecuta automáticamente.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run Serenity tests with full output
        run: |
          echo "CHROME PATH: $(which google-chrome)"
          google-chrome --version
          
          # Export required Chrome options
          export CHROME_BIN=google-chrome
          
          mvn clean verify \
            -Dwebdriver.driver=chrome \
            -Dchrome.headless=true \
            -Dchrome.switches="--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--window-size=1920,1080" \
            -Dserenity.console.headings=normal \
            -Dserenity.console.colors=true \
            -Dserenity.logging=VERBOSE \
            -Dserenity.reports.show.step.details=true \
            -Dserenity.outputDirectory=target/site/serenity \
            -Dmaven.test.failure.ignore=true \
            -B -e -X
        env:
          JAVA_OPTS: "-Xmx2048m"

      - name: List target directory contents
        run: ls -R target/site

      - name: Debug directory structure
        run: |
          echo "Verificando estructura del proyecto..."
          ls -R

      - name: Mostrar contenido de target
        if: always()
        run: |
          echo "Contenido del directorio target:"
          ls -R target

      - name: Archive Serenity Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
          if-no-files-found: warn