name: automated-testing-integration-PRTF
# este pipeline realiza la marcación en XRay de los casos de prueba ejecutados según el resultado obtenido.
# IMPORTANTE: Este pipeline no se ejecuta de forma automática, para su ejecución se debe dar clic en Run-workflow desde Github
on:
  workflow_dispatch:
    inputs:
      cucumber-tag:
        description: 'Tag de cucumber a ejecutar'
        required: false
        default: '@tag' # Tag predeterminado

jobs:
  integration-e2e-tests-site:
    if: github.ref == 'refs/heads/master'
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        include:
          - commands: >
              mvn clean verify -Denvironment=remote -D"cucumber.filter.tags=${{ github.event.inputs.cucumber-tag }}" -P"Regresion"
    uses: bancodebogota/bbog-dig-do-testing-pipeline/.github/workflows/test_frontend_integration.yml@v7
    with:
      java-version: 22
      aws-region: "us-east-1"
      command-install: ""
      command-execute: ${{ matrix.commands }}
      files-to-export: >
        target/site/serenity/serenity-summary.html
        target/serenity-reports/logback-report.txt
      prefix-team: 'xxxxx' # cambiar las xxxxxxx por el prefijo del equipo que se encuentre en Agile Teams
      use-aws-credentials: false
      debug: false
      environment: 'st' # ambiente de ejecución (staging)
      path-report-file: target/serenity-reports/cucumber_report.json
      test-plan-key: XXX-XXX # cambiar las xxxxx por el nombre del test plan, ejemplo (POT-806)
      test-exec-key: XXX-XXX # cambiar las xxxxx por el nombre del test execution, ejemplo (POT-812)
      browserstack-build-name: "XXXXX-xxx" # Variable definida para el nombre de la ejecución en browserstack, ejemplo (PRTF_login)
      browserstack-project-name: "XXXX-XXXXX" # Variable definida para el nombre del proyecto en browserstack, ejemplo (PRTF_Portafolio)
      repository: 'bbog-xxxxx-xxxxx-automated-testing' # Nombre del repositorio tal cual en Github, ejemplo bbog-prtf-portafolios-automated-testing
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      CLIENT_ID_XRAY: ${{ secrets.CLIENT_ID_XRAY }}
      CLIENT_SECRET_XRAY: ${{ secrets.CLIENT_SECRET_XRAY }}
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
      OTHERS: >
        BROWSERSTACK_USER=${{ secrets.BROWSERSTACK_USER }}
        BROWSERSTACK_KEY=${{ secrets.BROWSERSTACK_KEY }}
        CLIENT_ID_XRAY=${{ secrets.CLIENT_ID_XRAY }}
        CLIENT_SECRET_XRAY=${{ secrets.CLIENT_SECRET_XRAY }}